name: Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Type check
        run: tsc
      - name: Lint
        run: npm run lint
      - name: Prettier
        run: npm run prettier
      - name: Prettier
        run: npm run prettier
      - name: Jest
        run: npm run jest
